NREL-Sienna/PowerSystems.jl

- src/models/conventional_generation.jl
- src/models/hydro_generation.jl
- src/models/topological_elements.jl
- src/utils.jl
- test/readnetworkdata.jl
Update the folder reference in tests and a minor change to ordered limits
> Update after folder rename

- data/data_14bus.jl
- data/data_5bus.jl
- notebooks/Parametric Testing of dispatch.ipynb
- notebooks/System Modeling and Dispatching.ipynb
- src/PowerSystems.jl
- src/base.jl
- src/models/generation/thermal_generation.jl
- src/models/storage/batteries.jl
- src/parsers/dict_to_struct.jl
- test/constructors.jl
- test/powersystemconstructors.jl
Changed the naming convention for Thermal Generation and made it more consistent with the rest of the devices.
> Naming changes changes

- src/base.jl
- src/models/branches/lines.jl
- src/models/branches/transformers.jl
- src/models/generation/hydro_generation.jl
- src/models/generation/renewable_generation.jl
- src/models/generation/thermal_generation.jl
- src/models/loads/electric_loads.jl
- src/models/loads/shunt_elements.jl
- src/models/storage/batteries.jl
> Typo fixes

- README.md
- src/models/branches/lines.jl
> Powersystems wraupup

- src/PowerSystems.jl
- src/models/branches/dc_lines.jl
- test/checks_testing.jl
- test/constructors.jl
- test/powersystemconstructors.jl
- test/readnetworkdata.jl
- test/runtests.jl
Added Dc line support for two types of models and consistent Abstract hierarchy. 
Also improved the testing code in general. Closes #52
> Dcline modeling

- Manifest.toml
- Project.toml
- src/PowerSystems.jl
- src/parsers/dict_to_struct.jl
- src/parsers/forecast_parser.jl
- src/parsers/pm2ps_parser.jl
- test/parsestandard.jl
- test/readforecastdata.jl
- test/runtests.jl
addresses #64 
depends on a [PowerModels#moi-julia-v0.7 PR](https://github.com/lanl-ansi/PowerModels.jl/commit/b21a25dd698868d536bd1dd498504ef92b3094b7) to fix the dclines parsing
> Fix parsing

- src/parsers/dict_to_struct.jl
- src/parsers/standardfiles_parser.jl
- test/parsestandard.jl
> Fix per unit

- Project.toml
- REQUIRE
> update package version in Project.TOML

- .codecov.yml
- src/parsers/cdm_parser.jl
- src/parsers/dict_to_struct.jl
- src/parsers/forecast_parser.jl
- test/cdmparse.jl
- test/parse_matpower.jl
- test/runtests.jl
- updates the cdm parser and fixes bugs
- updates the times eries assignment to improve flexibilitiy
- requires update of powersystemstestdata
> Fix cdmparser

- .gitignore
- src/PowerSystems.jl
- src/base.jl
- src/models/generation.jl
- src/utils/print.jl
- src/utils/print_timearray.jl
- test/printing.jl
- test/runtests.jl
- converted NamedTuple for generators to a dedicated structure, "GenClasses" 
- smart printing of PowerSystem type
- overload of summary command (in addition to show) for PowerSystem (and the new GenClasses) -- helpful with output of varinfo()
> ravamped printing of PowerSystem type

- src/PowerSystems.jl
- src/base.jl
- src/models/loads.jl
- src/models/loads/controllable_loads.jl
- src/models/loads/electric_loads.jl
- src/models/products/reserves.jl
- src/parsers/cdm_parser.jl
- src/parsers/dict_to_struct.jl
- src/parsers/json2ps_parser.jl
- src/parsers/pm2ps_parser.jl
- test/constructors.jl
- test/printing.jl
> Update loads data model code

- src/PowerSystems.jl
- src/models/forecasts.jl
- src/models/generation/hydro_generation.jl
- src/models/generation/renewable_generation.jl
- src/models/generation/thermal_generation.jl
- src/models/loads/controllable_loads.jl
- src/models/loads/electric_loads.jl
- src/models/network.jl
- src/models/products/reserves.jl
- src/parsers/cdm_parser.jl
- src/parsers/dict_to_struct.jl
- src/parsers/forecast_parser.jl
- src/parsers/json2ps_parser.jl
- src/parsers/pm2ps_parser.jl
- src/parsers/pm_io/multiconductor.jl
- src/utils/IO/base_checks.jl
- src/utils/IO/system_checks.jl
- src/utils/lodf_calculations.jl
- src/utils/print.jl
- src/utils/print_timearray.jl
- src/utils/ptdf_calculations.jl
- src/utils/ybus_calculations.jl
- test/branchchecks_testing.jl
- test/readforecastdata.jl
> Remove using

- src/PowerSystems.jl
- src/models/topological_elements.jl
- test/constructors.jl
> Missing testing

- src/parsers/cdm_parser.jl
- src/parsers/dict_to_struct.jl
- src/parsers/forecast_parser.jl
- src/parsers/pm2ps_parser.jl
- src/parsers/pm_io/data.jl
- src/parsers/standardfiles_parser.jl
Merge my primarily editorial edits (comments and docstrings) of some of the parsing code.
> Psdict working jjs

- src/parsers/forecast_parser.jl
- test/readforecastdata.jl
The `name` argument was not being used.
> remove name::String argument from make_forecast_dict()

- .travis.yml
- docs/Manifest.toml
- docs/Project.toml
- docs/make.jl
This will generate documentation on Travis-CI and push to gh-pages automatically.
> Generate Documentation on CI

- src/parsers/pm_io/data.jl
This will partially fix issue #173.
> Fixed method overwrite problem in power model parser

- src/parsers/cdm_parser.jl
> Eliminated use of tryparse in cdm_parser.

- src/PowerSystems.jl
- src/parsers/dict_to_struct.jl
Resolves #166 
Also fixes some whitespace
> Remove Base.convert

- README.md
- docs/src/man/logging.md
- docs/src/man/tests.md
- src/PowerSystems.jl
- src/common.jl
- src/parsers/dict_to_struct.jl
- src/parsers/pm2ps_parser.jl
- src/parsers/pm_io/data.jl
- src/utils/IO/branchdata_checks.jl
- src/utils/IO/system_checks.jl
- src/utils/logging.jl
- test/runtests.jl
- test/test_logging.jl
This will fix issue #78.  The MultiLogger object could be moved to a 3rd-party module.  I'm proposing that we experiment with it here first.
> Logging improvements

- src/utils/data.jl
- make `branch` keyword only arguments
- re-indent code to be consistent with Julia style guide
> Add `branch` as keyword argument to download function

- src/base.jl
- src/utils/utils.jl
- test/cdmparse.jl
Looks like the previous PR was merged prematurely.  This is a continuation that addresses comments from that one.
> ConcreteSystem review continued

- Project.toml
- README.md
Change version and release to work with the master of PowerSimulations.
> change version number

- Manifest.toml
- src/base.jl
- src/models/branches/dc_lines.jl
- test/powersystemconstructors.jl
- test/test_system.jl
> Annex nothing cases

- src/PowerSystems.jl
- src/base.jl
> update output of get_components

- src/parsers/dict_to_struct.jl
- src/parsers/pm2ps_parser.jl
- closes #222 
- closes #223 via a patch to master *note: merging #206 will also resolve #223*
> Fix parsing bugs

- src/PowerSystems.jl
- src/base.jl
- src/parsers/forecast_parser.jl
- src/utils/print.jl
- test/busnumberchecks.jl
- test/cdmparse.jl
- test/powersystemconstructors.jl
- test/printing.jl
- test/test_system.jl
This PR:
- renames `System` to `_System`
- renames `ConcreteSystem` to `System` and routes all construction of `System` through the construction of `_System`
> Elevate system

- src/models/forecasts.jl
> Forecast length

- docs/src/man/data.md
- src/PowerSystems.jl
- src/base.jl
- src/models/forecasts.jl
- test/printing.jl
- test/test_system.jl
Fixes issues #238 and #216.  This is incomplete because the parsing code produces forecasts that match the spec'd behavior in #238.
> Refactored storage of forecasts within System.

- src/base.jl
- src/models/serialization.jl
- test/test_serialization.jl
This fixes issue #275 and #277
> Fix serialization of complex numbers.

- src/PowerSystems.jl
- src/models/forecasts.jl
- src/models/serialization.jl
- test/test_serialization.jl
> Fix serialization of Probabilistic forecasts.

- src/parsers/timeseries_formats.jl
- src/utils/IO/base_checks.jl
Fixes issue where forecasts with repeated periods were mishandled.
> Fixed forecast period handling

- src/parsers/timeseries_formats.jl
Fixes TimeseriesFormatPeriodAsColumn when the period is repeated.
This is a comparable fix as my previous PR, just with a different timeseries format.
> Fix forecast period

- src/common.jl
> add AER aggreated Fuel Codes

- src/models/forecasts.jl
- src/models/serialization.jl
This should fix issue #301. It will also allow other software to more easily work with serialized System objects.
> Simplified forecast serialization

- src/utils/network_calculations/common.jl
- src/utils/network_calculations/lodf_calculations.jl
- src/utils/network_calculations/ptdf_calculations.jl
- src/utils/network_calculations/ybus_calculations.jl
> Fix type inference on PowerNetworkMatrix

- src/parsers/im_io/common.jl
- src/parsers/im_io/data.jl
- src/parsers/im_io/matlab.jl
- src/parsers/pm2ps_parser.jl
- src/parsers/pm_io/common.jl
- src/parsers/pm_io/data.jl
- src/parsers/pm_io/matpower.jl
- src/parsers/pm_io/psse.jl
- src/parsers/pm_io/pti.jl
- src/utils/IO/branchdata_checks.jl
- test/branchchecks_testing.jl
- test/parse_matpower.jl
- test/parse_psse.jl
- updates PM and IM parsing code to version from:
- PM: https://github.com/lanl-ansi/PowerModels.jl/commit/27353b6d25a9e19d58091ec85cb36e27fce2bb31
- IM: https://github.com/lanl-ansi/InfrastructureModels.jl/commit/10d68fd8d8939a82ff9505633e434f63889e9992
closes #185
> Update pm parsers

- .travis.yml
- Manifest.toml
- Project.toml
- README.md
This PR will officially remove the support for Julia 1.1.
> Remove 1.1 from files

- bin/generate_structs.jl
- src/descriptors/power_system_structs.json
- src/models/generated/Bus.jl
- src/models/generated/TechHydro.jl
- src/models/generated/TechRenewable.jl
- src/models/generated/TechThermal.jl
> Fixes formatting issues with auto-generated code

- src/base.jl
- src/utils/print.jl
- test/printing.jl
This extends Jonathan's work and makes it compatible with the new InfrastructureSystems module.
> Printing enhancements

- Manifest.toml
- src/parsers/power_system_table_data.jl
> Fix rts load

- src/parsers/power_system_table_data.jl
This PR addresses the creation of PWL functions from table data.
> Fix rts cost

- src/base.jl
- test/test_validation.jl
This will resolve InfrastructureSystems.jl issue 13 - https://github.com/NREL/InfrastructureSystems.jl/issues/13.
> Add unit test and examples to docstring.

- src/base.jl
> Adopted new function name.

- src/parsers/pm2ps_parser.jl
- src/parsers/standardfiles_parser.jl
- enables custom validation descriptors via pm parsing 
- enables multiple loads per bus via pm parsing
> enabling multiple loads per bus via pm parsing

- CHANGELOG.md
- src/utils/power_flow/make_pf.jl
- test/test_powerflow.jl
> Pf indexing

- src/base.jl
> Fixes call to generate_initial_times.

- src/PowerSystems.jl
- src/base.jl
- test/test_busnumberchecks.jl
- test/test_system.jl
This will fix issue and close #364
> Enforce unique bus numbers

- src/PowerSystems.jl
- src/base.jl
- test/runtests.jl
- test/test_readforecastdata.jl
- test/test_serialization.jl
- test/test_system.jl
In addition to updating the test data branch this PR fixes:
- Add option in generate_initial_times to specify start time.
- issue #378
> Update test data branch

- src/descriptors/power_system_inputs.json
- src/models/devices.jl
- Resolves #403 
- defines reserve requirement in terms of system per unit
> Fix service bugs

- src/parsers/power_system_table_data.jl
- creates HydroFix when hydro storage data not available in tabledata, otherwise, creates HydroDispatch objects.
> Tabledata hydro bug

- src/descriptors/power_system_inputs.json
- src/parsers/power_system_table_data.jl
This addresses my comments in https://github.com/NREL/PowerSystems.jl/pull/408.
> Convert to standard parsing scheme

- src/descriptors/power_system_inputs.json
- src/parsers/common.jl
- src/parsers/generator_mapping.yaml
- src/parsers/power_system_table_data.jl
- src/utils/print.jl
- test/test_printing.jl
> supporting HydroFix parsing in table data

- src/utils/data.jl
> Get location from 7z at runtime

- bin/generate_config_file.py
- docs/make.jl
- docs/src/developer/extending_parsing.md
- docs/src/man/parsing.md
Markdown-rendered view of the files:
- https://github.com/daniel-thom/PowerSystems.jl/blob/parsing-docs/docs/src/man/parsing.md
- https://github.com/daniel-thom/PowerSystems.jl/blob/parsing-docs/docs/src/developer/extending_parsing.md
> Add parsing documentation

- src/PowerSystems.jl
- src/base.jl
- src/utils/IO/branchdata_checks.jl
- test/test_powersystemconstructors.jl
Adds a simple conversion between Line and MonitoredLine. I'm interested in thoughts on whether or not we should enable this.
> Linetype conversion

- src/utils/IO/branchdata_checks.jl
> fix SIL calculation and error message

- src/parsers/power_system_table_data.jl
This depends on PowerSystemsTestData branch=remove-unused-columns.
> Fix warnings that occur while parsing RTS data

- src/base.jl
- src/parsers/pm_io/psse.jl
- src/parsers/power_models_data.jl
- src/parsers/power_system_table_data.jl
- src/utils/IO/system_checks.jl
- src/utils/network_calculations/lodf_calculations.jl
- test/runtests.jl
- test/test_parse_matpower.jl
- test/test_power_system_table_data.jl
- test/test_system.jl
> adding system check for critical components

- src/base.jl
- src/descriptors/power_system_structs.json
- src/models/generated/Bus.jl
- src/parsers/pm_io/psse.jl
- src/parsers/power_models_data.jl
- src/parsers/power_system_table_data.jl
- src/utils/network_calculations/lodf_calculations.jl
- test/runtests.jl
- test/test_busnumberchecks.jl
- test/test_parse_matpower.jl
- test/test_power_system_table_data.jl
> Make area and load_zone optional for Bus

- src/PowerSystems.jl
- src/base.jl
- src/parsers/TAMU_data.jl
- src/parsers/power_models_data.jl
- test/runtests.jl
- test/test_parse_psse.jl
- test/test_parse_tamu.jl
- test/test_validation.jl
- adds a parser for tamu cases
- catches issues with branch endpoints at different voltage levels to create transformers
requires data from: https://github.com/NREL-SIIP/PowerSystemsTestData/pull/25
> tamu parser

- src/base.jl
This fixes a bug where the value for frequency was not being
deserialized.  issue #468
> Automatically deserialize optional System fields

- src/base.jl
- test/test_serialization.jl
> Override deepcopy for System

- src/descriptors/power_system_structs.json
This depends on changes in IS in https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/98
> Add validation descriptors for RegulationDevice

- test/test_readforecastdata.jl
> forgot one

- src/base.jl
- src/models/static_models.jl
This PR allows the user to create a custom device without requiring the implementation of services.
> update the addition of services 

- src/models/operational_cost.jl
handling case where variable cost gives a first point of 0.0, 0.0
> pwl-origin-cost

- Project.toml
- src/PowerSystems.jl
- src/base.jl
- src/models/devices.jl
- src/models/operational_cost.jl
- src/models/supplemental_accessors.jl
- src/models/topological_elements.jl
- src/parsers/TAMU_data.jl
- src/parsers/power_system_table_data.jl
Updated DocStringExtensions to latest version that fixes issues with
TYPEDSIGNATURES.
> Use DocStringExtensions TYPEDSIGNATURES

- src/descriptors/power_system_inputs.json
- src/parsers/pm_io/common.jl
- src/parsers/power_system_table_data.jl
@claytonpbarrows I made a separate PR for this. Feel free to push into it to wrap this issue up.
> table data parsing

- src/PowerSystems.jl
- src/base.jl
- src/utils/power_flow/power_flow.jl
Helper function to change system unit base
> add set base system

- src/base.jl
- src/models/dynamic_branch.jl
- src/models/serialization.jl
- test/test_serialization.jl
Depends on https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/107
> Fix serialization dynamic branch

- src/common.jl
- src/models/components.jl
- src/models/dynamic_generator.jl
- test/test_system.jl
Some additional changes to make dev06 work well.
> psi06 patches

- src/models/devices.jl
- src/models/regulation_device.jl
Requires https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/108
> Regulation device improvements

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/dynamic_machines.jl
- src/models/generated/RoundRotorMachine.jl
- src/models/generated/includes.jl
- test/test_dynamic_generator.jl
The following PR:
- Exports additional functions that were not being exported.
- Update the saturation function for parameters.
- Compute auxiliary parameters directly in the struct.
- Update saturation tests
> Update GENROU struct

- src/descriptors/power_system_structs.json
- src/models/generated/ThermalStandard.jl
Add more default values to the `ThermalStandard` fields. I added the same values as the null ones.
Please let me know if editing the JSON is all I need to do for this change.
> Add more defaults to ThermalStandard

- docs/make.jl
- docs/src/developer/adding_types.md
- src/base.jl
- src/models/devices.jl
- src/models/serialization.jl
- test/test_serialization.jl
- test/test_services.jl
I added documentation in this PR to make it easier for future contributors.  I think that documentation needs more content.  I intend this to be a starting point, not something final.
> Fix serialization for StaticReserveGroup

- src/base.jl
- src/models/regulation_device.jl
closes #573 but the serialization broke. Any hints @daniel-thom ?
> regulation device patch

- src/descriptors/power_system_structs.json
- src/models/generated/StaticReserve.jl
- src/models/generated/VariableReserveNonSpinning.jl
Adds operating costs to reserves (Static and variable)
> Add costs to reserves

- src/descriptors/power_system_structs.json
- src/models/generated/Line.jl
- src/models/generated/MonitoredLine.jl
- src/models/generated/PhaseShiftingTransformer.jl
- src/models/generated/TapTransformer.jl
- src/models/generated/Transformer2W.jl
> change errors to warn

- src/base.jl
- test/common.jl
- test/test_busnumberchecks.jl
- test/test_devices.jl
- test/test_network_matrices.jl
- test/test_powerflow.jl
- test/test_powersystemconstructors.jl
- test/test_validation.jl
This is a breaking change for any script that constructs a System from vectors of components.  This should be easier for users to understand and use.
> Simplify System constructor

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/generated/ZeroOrderBESS.jl
- src/models/generated/includes.jl
- test/test_dynamic_inverter.jl
Created a struct for a zero order battery energy storage system to capture DC-side dynamical behavior. Includes representation of battery, DC/DC converter and DC/DC controller
> Added struct for Zero Order Battery Model (ZeroOrderBESS.jl)

- src/base.jl
- src/models/devices.jl
- test/test_services.jl
> service addition to device

- src/PowerSystems.jl
- src/models/reserves.jl
- test/test_services.jl
Adds a symmetric `ReserveDirection`.
> Add a Symmetric ReserveDirection

- docs/src/model_developer/market_bid_cost.md
- src/models/cost_function_timeseries.jl
> Adding documentation for MarketBidCost

- src/utils/network_calculations/ybus_calculations.jl
- src/utils/power_flow.jl
- test/data_14bus_pu.jl
- test/test_powerflow.jl
The previous version of the power flow solve didn't consider the availability of devices
> include available in pf

- src/utils/data.jl
I added an additional method to download data from any arbitrary repository since we have users of the RTS-GMLC repo and soon an extended solar case for ERCOT.
> add new download method to UtilsData

- src/models/RoundRotorExponential.jl
- src/models/RoundRotorQuadratic.jl
- src/models/SalientPoleExponential.jl
- src/models/SalientPoleQuadratic.jl
- test/test_parse_dynamics.jl
> dyn gen deserialization

- src/base.jl
- test/common.jl
- test/test_serialization.jl
- test/test_validation.jl
> Fix handling of skip_validation flag

- src/models/dynamic_models.jl
Make some minor changes to integrate with PSID
> psid updates

- src/utils/network_calculations/lodf_calculations.jl
- src/utils/network_calculations/ptdf_calculations.jl
Add sorting to the buses in PTDF
> add sort to PTDF

- src/base.jl
- src/parsers/pm_io/data.jl
- src/parsers/power_models_data.jl
- addresses #687 by indicating resolutions in error messages.
- requires https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/191
> adding better error messages for pti parsing

- src/base.jl
- src/parsers/TAMU_data.jl
- src/parsers/pm_io/common.jl
- src/parsers/power_models_data.jl
this PR passes kwargs through to parse_file to allow for control on pm_validation routines
> minor pm parser_updates

- src/base.jl
> Fix handling of System kwargs in deserialize

- src/base.jl
- test/common.jl
> bus number serialization

- src/models/components.jl
minor additions to avoid warning messages.
> adding convert methods for more field types

- src/models/serialization.jl
> Fix ambiguity

- src/PowerSystems.jl
> add missing export/imports

- docs/src/model_developer_guide/adding_custom_types.md
- src/utils/print.jl
> Fix printing of non-PowerSystems components

- src/base.jl
- test/test_system.jl
> Allow changing the name of a component that is in a system

- src/models/components.jl
- src/models/generated/BatteryEMS.jl
- src/models/generated/GenericBattery.jl
- src/models/generated/HVDCLine.jl
- src/models/generated/HydroDispatch.jl
- src/models/generated/HydroEnergyReservoir.jl
- src/models/generated/HydroPumpedStorage.jl
- src/models/generated/InterruptibleLoad.jl
- src/models/generated/Line.jl
- src/models/generated/MonitoredLine.jl
- src/models/generated/PhaseShiftingTransformer.jl
- src/models/generated/PowerLoad.jl
- src/models/generated/RenewableDispatch.jl
- src/models/generated/RenewableFix.jl
- src/models/generated/TapTransformer.jl
- src/models/generated/ThermalMultiStart.jl
- src/models/generated/ThermalStandard.jl
- src/models/generated/Transformer2W.jl
- src/models/generated/VSCDCLine.jl
Fixes #763 
Needs IS PR#244 to be merged and tagged to pass test.
> Adding a set_value function to convert values to the correct unit system

- src/utils/power_flow.jl
This PR fixes a bug introduced in #769 that broke the power flow calculations.
> remove conversion

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/generated/PeriodicVariableSource.jl
- src/models/generated/Source.jl
- src/models/generated/includes.jl
- test/test_dynamics_source.jl
@m-bossart and @rodrigomha this is the struct for the periodic variable source. Assuming that 
```latex
V(t) = 1/2a_0_v + \sum_i^n_freq coeff_v[i][1] * sin(\omega t) + coeff_v[i][2]*cos(\omega t)
```
and there is an equivalent function 
```latex
\theta(t) = 1/2a_0_ang + \sum_i^n_freq coeff_ang[i][1] * sin(\omega t) + coeff_ang[i]*cos(\omega t)
```
> periodic variable source

- src/descriptors/power_system_structs.json
- src/models/generated/PeriodicVariableSource.jl
- src/utils/network_calculations/ybus_calculations.jl
- test/test_dynamics_source.jl
Add base_power to PeriodicVariableSource so it can be added to a system.
Modify existing test to add to a system
> Fix for PeriodicVariableSource 

- src/descriptors/power_system_structs.json
- src/models/generated/PeriodicVariableSource.jl
- test/test_dynamics_source.jl
> remove bus from periodic source

- docs/src/modeler_guide/parsing.jl
- docs/src/modeler_guide/time_series.md
- src/base.jl
- test/test_serialization.jl
- test/test_system.jl
This is dependent on https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/252.
> Update docs to describe new environment variable

- src/utils/power_flow.jl
There was a bug when writing the power flow solution that was not ignoring the unavailable generators.
> Fix power flow dataframe solution

- Project.toml
- src/PowerSystems.jl
- src/base.jl
- src/parsers/enums.jl
- src/parsers/power_system_table_data.jl
- src/utils/IO/branchdata_checks.jl
- test/test_system.jl
> Remove check_sil from add_component! call stack

- src/descriptors/power_system_inputs.json
- src/parsers/common.jl
- src/parsers/power_system_table_data.jl
adding some flexibility to the tabular parser:
- removed requirement for bus_id column and defaulting id's based on row order
- handles NA fuel entries
- improved some flexibility on Int->Float conversion
> improving flexibility of table data parsing

- Project.toml
- src/utils/network_calculations/common.jl
Changes `_make_ax_ref` to use AbstractVector
> Use AbstractVector in _make_ax_ref

- src/utils/network_calculations/ybus_calculations.jl
> add ybus data checks

- src/models/dynamic_generator_components.jl
- src/models/dynamic_machines.jl
- test/test_dynamic_generator.jl
Fix a bug when computing saturation coefficients for Synchronous Machines.
> Fix Saturation calculations

- src/PowerSystems.jl
- src/base.jl
- src/models/static_injection_subsystem.jl
> Use IS.copy_time_series! directly

- src/descriptors/power_system_inputs.json
- src/parsers/power_system_table_data.jl
> handling bus shunts in tabular parser

- src/descriptors/power_system_structs.json
- src/models/generated/STAB1.jl
- src/models/generated/includes.jl
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR: 
Check the [contributor guidelines](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Add a description of the changes proposed in the pull request. 
2. Is my PR fixing an open issue? Add the reference to the related issue 
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)
> include struct for STAB1 

- src/descriptors/power_system_structs.json
- src/models/generated/AggregateDistributedGenerationA.jl
- test/test_dynamic_generator.jl
Adds base_power field to AggregateDistributedGenerationA. 
Add a test for adding AggregateDistributedGenerationA to a system.
> Fix AggregateDistributedGenerationA 

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/dynamic_loads.jl
- src/models/generated/SimplifiedSingleCageInductionMachine.jl
- src/models/generated/SingleCageInductionMachine.jl
- src/models/generated/includes.jl
- test/test_dynamic_loads.jl
@jd-lara I think we may want to go at some point with adding DynamicLoad abstract at some point.
From this point onwards we are expecting to add more and more Dynamic Load models, so it may be a good idea to think a strategy for that.
> Add induction motors structs

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/generated/StandardLoad.jl
- src/models/generated/includes.jl
Add new struct for standard load.
> add standard load

- README.md
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR: 
Check the [contributor guidelines](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Add a description of the changes proposed in the pull request. 
2. Is my PR fixing an open issue? Add the reference to the related issue 
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)
> adding downloads badge

- src/descriptors/power_system_structs.json
- src/models/generated/InterconnectingConverter.jl
- src/models/generated/includes.jl
First approach on IPCs. This approach has a field for the acbus and a field for the dcbus.
> Adding Interconnecting Converters

- test/Project.toml
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR: 
Check the [contributor guidelines](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Add a description of the changes proposed in the pull request. 
2. Is my PR fixing an open issue? Add the reference to the related issue 
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)
> fix PSB version in tests

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/generated/InterconnectingConverter.jl
- src/models/generated/includes.jl
- src/parsers/powerflowdata_data.jl
With this update it is possible to create systems with AC/DC grids.
> Add IPCs to psy3

- src/PowerSystems.jl
- src/base.jl
- src/descriptors/power_system_structs.json
- src/models/generated/ACBus.jl
- src/models/generated/Arc.jl
- src/models/generated/DCBus.jl
- src/models/serialization.jl
- src/models/topological_elements.jl
- src/parsers/powerflowdata_data.jl
- test/runtests.jl
Here is a first approach for this. It is not working properly when deserializing a system with IPCs, DC Buses, DCBranches,
since for some reason is not able to find UUID.
> Address Deserialization issue

- src/base.jl
- src/models/serialization.jl
- test/test_serialization.jl
Tests will fail until IS gets a new tag from https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/309
> Check for invalid values in component ext

- src/descriptors/power_system_structs.json
- src/models/generated/CSVGN1.jl
- src/models/generated/includes.jl
Hello, I'm adding a new struct for the Static Shunt Compensator model CSVGN1.
> Add CSVGN1 Struct

- src/descriptors/power_system_structs.json
- src/models/generated/StaticReserve.jl
- src/models/generated/StaticReserveGroup.jl
- src/models/generated/StaticReserveNonSpinning.jl
- src/models/generated/VariableReserve.jl
- src/models/generated/VariableReserveNonSpinning.jl
This PR fixes #972, which will convert the requirement field for Reserves.
> Fixing unit conversion reserves 

- src/descriptors/power_system_structs.json
- src/models/generated/PSS2B.jl
- src/models/generated/includes.jl
Hello, I'm adding a new struct for the IEEE 421.5 2005 PSS2B IEEE Dual-Input Stabilizer Model.
> PSS2B struct

- docs/src/tutorials/basics.md
Seems that is ready for review
> Update Docs to PSY 3.0

- test/test_subsystems.jl
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR:
Check the [contributor guidelines](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Add a description of the changes proposed in the pull request.
2. Is my PR fixing an open issue? Add the reference to the related issue
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)
> Adding subsystem tests for 2 Area 5 bus system

- docs/make_model_library.jl
- src/models/static_injection_subsystem.jl
PSY portion of https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/339
> Use nameof instead of custom function

- docs/src/modeler_guide/time_series.md
- test/test_serialization.jl
Tied to https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/343
> Docs and tests for sharing time series data on a component across multiple fields

- src/PowerSystems.jl
- src/base.jl
- src/subsystems.jl
- test/test_subsystems.jl
> Construct a system from a subsystem

- docs/src/tutorials/basics.md
- src/PowerSystems.jl
- src/base.jl
- src/models/HybridSystem.jl
- src/models/cost_function_timeseries.jl
- src/models/static_injection_subsystem.jl
- src/utils/print.jl
- test/test_hybrid_system.jl
- test/test_printing.jl
- test/test_read_time_series.jl
- test/test_serialization.jl
- test/test_subsystems.jl
- test/test_system.jl
This PR is tied to the changes in https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/349.
> Support time series redesign in InfrastructureSystems

- src/descriptors/power_system_structs.json
- src/models/generated/AggregateDistributedGenerationA.jl
- src/parsers/psse_dynamic_data.jl
- src/parsers/psse_dynamic_mapping.yaml
This is a first idea on how to handle DynamicInjectors parsing on top of components.
> Add new parsing capabilities for DERA1

- src/PowerSystems.jl
- src/base.jl
- src/descriptors/power_system_structs.json
- src/models/cost_function_timeseries.jl
- src/models/cost_functions/MarketBidCost.jl
- src/models/generated/ReserveDemandCurve.jl
- src/utils/print.jl
- test/test_system.jl
Companion PR to https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/365
> Redefine TimeSeriesKey

- docs/src/modeler_guide/time_series.md
- docs/src/tutorials/modifying_data.md
- docs/src/tutorials/parse_tabular_data.md
- src/base.jl
Companion PR to https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/368.
Tests will work as soon as these PRs are merged:
- https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/370
- https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/369
- https://github.com/NREL-Sienna/PowerSystemCaseBuilder.jl/pull/90
> Accept Dates.Period in transform_single_time_series!

- src/models/cost_functions/variable_cost.jl
- test/test_cost_functions.jl
As discussed with @rodrigomha and @jd-lara. Straightforward here, but let's get a companion branch in PSI before merging?
> Make `vom_cost` a `LinearCurve` in `ProductionVariableCost`s, add tests

- src/base.jl
forwards https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/379
> forward method

- docs/src/api/public.md
- docs/src/modeler_guide/time_series.md
- src/PowerSystems.jl
- src/base.jl
Companion PR to https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/381
> Add function to add time series in bulk

- src/parsers/power_system_table_data.jl
> Update table data parser to work with WECC dataset

- docs/src/api/valuecurve_options.md
- docs/src/explanation/example_dynamic_data.md
- docs/src/explanation/system.md
- docs/src/explanation/type_structure.md
- docs/src/tutorials/working_with_time_series.md
Doing it in the main repo to see the preview
> Update broken pics links for docs

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/generated/TGSimple.jl
- src/models/generated/includes.jl
Add basic single state turbine governor struct
```
τ = P_ref + d_t * (ω_ref - ω)
d τm / dt = (τ - τm) / Tm
```
> add TGSimple model

- docs/src/how_to/market_bid_cost.md
> Update Market Bid docs typos

- src/descriptors/power_system_structs.json
- src/models/generated/EnergyReservoirStorage.jl
> add market bid to storage

- src/parsers/pm_io/psse.jl
- src/parsers/power_models_data.jl
Put RT, XT fields into the ext dictionary. Since ZR & ZX where already added.
> Add RT, XT, ZR, ZX parameters to ext dict for generator.

- src/PowerSystems.jl
- src/base.jl
- src/descriptors/power_system_structs.json
- src/models/generated/ACBus.jl
- test/test_system.jl
> Add set_bus_number!

- src/base.jl
Companion PR to https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/442
> transform_single_time_series! with resolution

- docs/src/how_to/build_system_with_files.md
> fixing reference issues

- src/parsers/pm_io/data.jl
- src/parsers/power_models_data.jl
This PR is related and closes issue #1308
> Fix fixed shunt naming & sw shunt scaling (pu)

- src/descriptors/power_system_structs.json
- src/models/branches.jl
- src/models/generated/Line.jl
- src/models/generated/MonitoredLine.jl
- src/models/generated/PhaseShiftingTransformer.jl
- src/models/generated/TapTransformer.jl
- src/models/generated/Transformer2W.jl
- src/models/generated/Transformer3W.jl
- src/models/generated/TwoTerminalGenericHVDCLine.jl
- src/models/generated/TwoTerminalLCCLine.jl
- src/models/generated/TwoTerminalVSCLine.jl
> add new branch organization

- .github/workflows/cross-package-test.yml
- src/data_format_conversions.jl
- src/models/supplemental_accessors.jl
- src/parsers/power_models_data.jl
- test/test_parse_psse.jl
We need some changes for Transformer3W functions to allow for its integration in PowerNetworkMatrices
> Changes for Transformer3W

- src/PowerSystems.jl
- src/utils/IO/branchdata_checks.jl
- test/test_dynamic_generator.jl
- test/test_parse_psse.jl
- test/test_system.jl
- Change errors and warn into warn and infos, respectively.
- Fix typo in export
- Update tests
> Line limits patch

- src/PowerSystems.jl
- src/outages.jl
should the name be `FixedOutage` or `FixedForcedOutage`?
> Change name for FixedOutage

- README.md
Add missing closed bracket, remove one last comma, and add indent.
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR:
Check the [contributor guidelines](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Add a description of the changes proposed in the pull request.
2. Is my PR fixing an open issue? Add the reference to the related issue
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)
> Fix bibtex on README.md

- src/definitions.jl
- src/descriptors/power_system_structs.json
- src/models/generated/DiscreteControlledACBranch.jl
- src/models/generated/includes.jl
closes #821 and partially #1017 
@mcllerena if this design works we can start implementing the parser for switches as described in #1017. 
@GabrielKS please check if this is enough to export to PSSe v33
> add new struct for switch/breaker

- src/PowerSystems.jl
- src/models/supplemental_constructors.jl
- src/parsers/enums.jl
- src/parsers/pm_io/psse.jl
- src/parsers/power_models_data.jl
- src/parsers/psse_metadata_reimport.jl
- test/test_parse_psse.jl
This a first approach for parsing Switches & Breakers elements using PSY.parse_psse.
Missing implementation for System creation (in progress)
> Parsing for switches & breakers

- docs/src/api/enumerated_types.md
- src/definitions.jl
- src/parsers/common.jl
List of changes
- Updated enums to include all the new thermal fuels listed [here](https://www.eia.gov/survey/form/eia_923/instructions.pdf)
- Updated docs to reflect new enums
Closes #1239
> feat: Adding updated list of thermal fuels from EIA

- src/parsers/power_models_data.jl
Converts lines to transformers based on a % difference threshold for the voltage endpoints. 
Fixes #1333
> base transformer conversion on % diff

- src/models/dynamic_branch.jl
add ratings b and c for dynamic branches for consistency
> B and C ratings for DynamicBranch

- src/PowerSystems.jl
- src/descriptors/power_system_structs.json
- src/models/cost_functions/ImportExportCost.jl
- src/models/generated/Source.jl
- src/models/supplemental_accessors.jl
- test/test_cost_functions.jl
Redoing it another branch since the rebase of json files is a mess lol.
> New Update to Import/Export structs

- src/descriptors/power_system_structs.json
@daniel-thom is this the right approach to add a minimum descriptor in the json file for a manually created struct?
Closes #1183
> Add descriptors for dynamic generator and inverter

- src/base.jl
> Remove obsolete method for remove_supplemental_attribute!

- src/parsers/power_models_data.jl
- test/test_parse_psse.jl
- test/test_powersystemconstructors.jl
- Update `impedance_correction_instances` with a Nothing type to handle missing ICT data.
- Update to `@info` message for ICT data
- Update component names  in tests to handle newest changes
> Update test and fix bug

- src/models/cost_functions/RenewableGenerationCost.jl
> add fixed term to renewable cost

- src/descriptors/power_system_structs.json
- src/models/generated/PhaseShiftingTransformer.jl
- src/models/generated/TapTransformer.jl
- src/models/generated/Transformer2W.jl
- src/models/generated/Transformer3W.jl
- src/models/generated/includes.jl
- src/parsers/pm_io/matpower.jl
- src/parsers/pm_io/psse.jl
- src/parsers/power_models_data.jl
- src/parsers/power_system_table_data.jl
- src/parsers/powerflowdata_data.jl
- test/data_14bus_pu.jl
Requires: https://github.com/NREL-Sienna/PowerSystemsTestData/pull/71
Tests are passing locally with exception of a serialization/deserialization minor issue with the ext that we have to fix later.
I have not tested extensively CaseBuilder, so still TBD to fix all the build systems.
> Add base power for transformers

- src/PowerSystems.jl
> export geo_json

- src/descriptors/power_system_inputs.json
- src/descriptors/power_system_structs.json
- src/models/generated/ACBus.jl
- src/models/generated/Line.jl
- src/models/generated/MonitoredLine.jl
- src/models/generated/PhaseShiftingTransformer.jl
Closes https://github.com/NREL-Sienna/PowerSystems.jl/issues/1335
> Remove angle limits checks

- docs/src/tutorials/creating_system.md
Edit example in doc to be compatible with `PowerFlows.jl`. This also solve https://github.com/NREL-Sienna/PowerSystems.jl/issues/1382.
> move ThermalStandard to bus1 for PowerFlows

- src/base.jl
- test/test_devices.jl
- test/test_services.jl
> Add removal validation for areas 

- src/models/HydroReservoir.jl
There is also an auxiliary method for passing a Float to create a LinearCurve if needed.
@rbolgaryn Can you confirm that the serialization works with this branch?
> Change h2v factor in HydroReservoir to ValueCurve

- src/PowerSystems.jl
- src/utils/IO/branchdata_checks.jl
- test/test_hydro_reservoir.jl
To review first that the unit conversion PR
> Transformer validation checks

- src/descriptors/power_system_structs.json
- src/models/generated/TwoTerminalVSCLine.jl
> update missing scaling fields

- src/descriptors/power_system_structs.json
- src/models/generated/ACBus.jl
- src/parsers/pm_io/psse.jl
- src/parsers/power_models_data.jl
This is another change that needs to be documented in the migration guide
> Add available to ACBus 

- src/PowerSystems.jl
- src/base.jl
- src/utils/print.jl
- test/test_parse_psse.jl
This requires code currently in IS main branch + https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/474, and so CI will fail.
> Add get_num_components for System

- src/PowerSystems.jl
- src/base.jl
- src/parsers/psse_dynamic_data.jl
- test/test_parse_dynamics.jl
- test/test_parse_psse.jl
- test/test_power_system_table_data.jl
- test/test_system.jl
This PR fixes the tests in PSY 5 using IS#main, PSTD#master, PSB#PSY5
> fix psy5 tests1

- docs/src/how_to/build_system_with_files.md
- docs/src/how_to/market_bid_cost.md
- docs/src/tutorials/creating_system.md
- docs/src/tutorials/working_with_time_series.md
Similar to https://github.com/NREL-Sienna/PowerSimulations.jl/pull/1328 but the only occurrences in PSY are in the docs.
> Add `available` to `ACBus` instantiation in docs

- src/parsers/pm_io/psse.jl
- src/parsers/power_models_data.jl
Fixes issue https://github.com/NREL-Sienna/PowerSystems.jl/issues/1469#issuecomment-3070720793
> Fix SC parsing logic

- src/parsers/pm_io/psse.jl
Three small fixes based on errors in the EI Ybus match with PSSE.
> bug  fixes for improved ybus match

- src/models/supplemental_accessors.jl
> make naming consistent for getting transformer angles 

- src/definitions.jl
- src/descriptors/power_system_structs.json
- src/models/generated/HydroDispatch.jl
- src/models/generated/HydroPumpTurbine.jl
- src/models/generated/HydroTurbine.jl
- src/models/generated/SynchronousCondenser.jl
- src/models/generated/includes.jl
Some more changes for enums and status are pending but this the general direction for the change. 
This might break some tests... so before merge it needs to run the tests. 
fixes: #1515 #1513
> add turbine enum

- src/base.jl
- src/models/supplemental_accessors.jl
This fixes the support services to make the PSI tests pass.
> add a fix for services tests in PSI

- src/utils/IO/system_checks.jl
- test/test_parse_dynamics.jl
- test/test_parse_matpower.jl
- test/test_parse_psse.jl
- test/test_powersystemconstructors.jl
- test/test_serialization.jl
Address issue #1525 and fix an unrelated test failure.
> Remove "no active gens found at PV" message and tests
