NREL-Sienna/PowerSystems.jl

src/base.jl, src/models/generation.jl
With this PR we get rid of the old sources struct and implement the classifier as originally designed using Named Tuples
=> Remove old genclassification

.travis.yml, Manifest.toml, Project.toml, src/parsers/pm_io/common.jl, src/parsers/pm_io/data.jl, src/parsers/pm_io/matpower.jl, src/parsers/pm_io/multiconductor.jl, src/parsers/pm_io/psse.jl, src/parsers/pm_io/pti.jl, src/utils/system_checks.jl, test/runtests.jl
This PR updates the parsing code from PM to version 0.9. It breaks compatibility with the pm2ps_dict parser since the data model in PM was updated. 
Bringing back the conversation about making a better version of the PS_dict, this is a good opportunity to undertake that task. The test for parse standard is commented out until we make the dicts compatible.
=> Update pm parser

test/cdmparse.jl, test/parse_matpower.jl, test/parse_psse.jl, test/printing.jl, test/readforecastdata.jl
@claytonpbarrows and @jjstickel  After the PM update and the change to Julia 1.1 parsing tests for some matpower files and some psse files started failing, those are commented out. 
Also, in Julia 1.1 the printing tests started failing. Seems that the command `String(take!(io))` is unhappy.
=> add test_skip to non working tests

src/PowerSystems.jl, src/base.jl, src/models/generation/tech_common.jl, src/models/topological_elements.jl
Some work on docstrings for PowerSystems (the module), the PowerSystem struct,  and structs in topological_elements, and tech_common. 
@jd-lara suggested merging and then continue adding/revising docstrings as we work on other tasks. I used the keyword `DOCTODO` to bring attention to docstring items to address.
=> Docstrings

deps/build.jl, src/PowerSystems.jl, src/utils/data.jl, test/data.jl, test/runtests.jl
**Usage**:
```julia
$ julia --project
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia> using PowerSystems
julia> download(PowerSystems.TestData)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   133    0   133    0     0    372      0 --:--:-- --:--:-- --:--:--   372
100 11.8M    0 11.8M    0     0  2764k      0 --:--:--  0:00:04 --:--:-- 3307k
"/Users/$USER/GitRepos/PowerSystems.jl/data"
shell> ls data
RTS_GMLC                data_14bus.jl …
```
=> Add download test data function

src/PowerSystems.jl, src/common.jl, src/models/branches/lines.jl, src/parsers/dict_to_struct.jl, src/parsers/im_io/common.jl, src/parsers/im_io/data.jl, src/parsers/im_io/matlab.jl, src/parsers/pm2ps_parser.jl, src/parsers/pm_io/data.jl, src/parsers/pm_io/multiconductor.jl, src/parsers/pm_io/pti.jl, src/utils/IO/base_checks.jl, src/utils/data.jl, test/branchchecks_testing.jl, test/busnumberchecks.jl, test/cdmparse.jl, test/constructors.jl, test/data.jl, test/network_matrices.jl, test/parse_matpower.jl, test/parse_psse.jl, test/powersystemconstructors.jl, test/readforecastdata.jl, test/runtests.jl
All unit tests now run and pass.
This pull request also has a few UT-execution enhancements:
- Instead of explicitly including all tests runtests.jl now automatically runs all "*.jl" in the test directory.
- You can now iterate on one or more unit tests by pushing a test name into ARGS while in the REPL.
- push!(ARGS, "parse_psse")
- include("test/runtests.jl")
- You can customize logging verbosity by setting the environment variable PS_LOG_LEVEL to Debug, Info, Warn, or Error.
You will also notice a different in unit test output.  When all tests pass it will show the total number of tests in PowerSystems.  If any test fails then it will print out a summary table showing the results of each test.  The difference is because of a top-level @testset statement that I added in runtests.jl.
=> Refactor parser unit tests and fix test failures.

src/base.jl, src/utils/IO/base_checks.jl, src/utils/IO/branchdata_checks.jl, src/utils/IO/system_checks.jl, test/test_base_checks.jl
=> Enforce ordering of bus and branch numbers in PowerSystem construction.

Manifest.toml, Project.toml, src/PowerSystems.jl, src/base.jl, src/parsers/generator_mapping.toml, src/parsers/generator_mapping.yaml, src/parsers/im_io/matlab.jl, src/parsers/pm2ps_parser.jl, src/parsers/pm_io/common.jl, src/parsers/pm_io/data.jl, src/parsers/standardfiles_parser.jl
A config file was implemented to map string designations of "fuel" and "type" for generators in PowerModels-type source data files to generator classifications in PowerSystems. The config file format is currently TOML because it is easy to read and modify by humans. Note, however, the TOML module that is compatible with Julia 1.x is not registered, and so it needed to be added via url (I tagged the commit that corresponds to release version 0.4.0).
I think this PR can close #131 .
Another note:  I noticed that some generator-device classifications are *not* currently mapped. Even though "Storage" is initialized in ps_dict["gen"], there was (and is) no code to assign anything to Storage. Another I noticed is CSP (concentrated solar power, I presume). These currently default to "Thermal".
=> implemented a generator-mapping config file

src/parsers/im_io/matlab.jl, src/parsers/pm_io/matpower.jl
The function parse_matlab_string created line indices based on how many
"\n" characters were present in the file. There was an off-by-one error
whenever the last character wasn't "\n".  The code would have not worked
at all if a file used line endings of "\r" (pre Mac OS X).
=> Fixed parsing of matpower files that don't end in newline

src/parsers/pm_io/data.jl
The validation code in the power model parser was logging errors for
invalid input data. This allowed runtime errors to occur later. Changed
the checks to throw an exception instead so that execution stops
immediately.
This should address issue #101.
=> Changed error prints to exceptions in power model parser.

src/utils/ybus_calculations.jl
I am on PowerSystems master and Julia 1.3 master and I could not get @jd-lara's [ybus calculation example](https://gist.github.com/jd-lara/adc17da9fc391db037722abcc108a3b4) to work. This fixed the first error. Now I am running into the error:
```
julia> Ybus = PowerSystems.build_ybus(length(Buses), Branches)
ERROR: type PhaseShiftingTransformer has no field zb
Stacktrace:
[1] getproperty(::Any, ::Symbol) at ./Base.jl:20
[2] ybus!(::SparseArrays.SparseMatrixCSC{Complex{Float64},Int64}, ::PhaseShiftingTransformer) at /home/coey/.julia/dev/PowerSystems/src/utils/ybus_calculations.jl:72
[3] build_ybus(::Int64, ::Array{Branch,1}) at /home/coey/.julia/dev/PowerSystems/src/utils/ybus_calculations.jl:135
[4] top-level scope at REPL[13]:1
```
=> fix spzeros function call

src/utils/print.jl
I think this you asked for something like this yesterday, but I may have forgotten a few things.
```
julia> rts_data
PowerSystems.PowerSystemTableData:
directory:  ../RTS-GMLC/RTS_Data/SourceData
timeseries_metadata_file:  ../RTS-GMLC/RTS_Data/SourceData/timeseries_pointers.csv
basepower:  100.0
branch:  120×14 DataFrames.DataFrame
bus:  73×15 DataFrames.DataFrame
dcline:  1×60 DataFrames.DataFrame
gen:  158×57 DataFrames.DataFrame
load:  no data
services:  7×5 DataFrames.DataFrame
```
=> Simplify printing for PowerSystemTableData

src/base.jl, src/descriptors/power_system_structs.json, src/models/generated/TechHydro.jl, src/models/generated/TechRenewable.jl, src/models/generated/TechThermal.jl, src/models/generated/VSCDCLine.jl, src/models/generation.jl, src/parsers/power_system_table_data.jl, test/runtests.jl, test/test_readforecastdata.jl, test/test_serialization.jl, test/test_system.jl
There is one thing not done here:  When calling add_forecast there is no validation that the label translates to a function that is callable on the component.  I'll wait to do that until you guys take a first pass on the implementation.
Note that it would be trivial to change label from accessor function to fields.
Also note that I DID create a branch in PowerSystemsTestData in support of these changes but NOT the RTS_GMLC repo.
=> Change forecast labels to component accessor functions

CHANGELOG.md, Project.toml, src/descriptors/power_system_inputs.json, src/models/supplemental_constructors.jl
- creates a superset of heat rate traunches to support parsing up to 13 point heat rate curves
=> Extended hr cols

src/PowerSystems.jl, src/base.jl, test/test_system.jl
I did not add this option described in the story:
```
One more optional thing to consider is making the forecast type be default to Deterministic and leave it to the modeler/user to get a different type of forecast if present.
```
I think that doing this would mean that we change all forecast methods.  Would you want to do that?
=> Add methods for get_forecast_values

src/base.jl, test/test_serialization.jl, test/test_validation.jl
Note that I deviated from the workflow discussed today.  The JSON filename is the basis of the interface, not the directory.
Fixes issue #472
=> Support moving serialization files to new path

src/descriptors/power_system_structs.json, src/models/generated/AVRFixed.jl, src/models/generated/AVRSimple.jl, src/models/generated/AVRTypeI.jl, src/models/generated/AVRTypeII.jl, src/models/generated/AndersonFouadMachine.jl, src/models/generated/BaseMachine.jl, src/models/generated/FullMachine.jl, src/models/generated/MarconatoMachine.jl, src/models/generated/OneDOneQMachine.jl, src/models/generated/ReactivePowerDroop.jl, src/models/generated/SimpleAFMachine.jl, src/models/generated/SimpleFullMachine.jl, src/models/generated/SimpleMarconatoMachine.jl, src/models/generated/TGFixed.jl, src/models/generated/TGTypeI.jl, src/models/generated/TGTypeII.jl, src/models/generated/VirtualInertia.jl, src/models/generated/includes.jl, test/test_dynamic_generator.jl
The following PR provides an update on the dynamic structures for better integration to the dynamic models.
The main changes are:
- Add `V_ref` to the AVR models and OuterControl models. This is a parameter that defaults to 1.0, and must be updated when initializing the dynamic model via the solution of the static Power Flow.
- Add `P_ref` to the TurbineGov models and OuterControl models. Also defaults to 1.0.
- Remove `MVABase` from machine. This parameter should be the same as the base power provided in the static generator structs.
Note that `V_ref` and `P_ref` are not necessarily the solution of the static power flow model. These parameters will depend on the specific dynamic models used, and must be updated in order to match solutions of the static PF with the initial condition of …
=> Update Dynamic Structs

src/parsers/power_models_data.jl, src/utils/power_flow/make_pf.jl
The following PR adds some optimizations in solving the power flow. Namely:
- We create a neighbor array that is used to only access branches that are neighboring each bus.
- Update a fixed admittance bug.
- Remove additional counters.
=> Updates on PowerFlow solver

src/base.jl, src/descriptors/power_system_structs.json, src/models/generated/Bus.jl, src/models/serialization.jl
This will definitely break deserialization from previous versions because we were storing areas and load zones as objects instead of UUIDs in the JSON.  We were also allowing addition of buses if attached areas and load zones were not part of the system.
=> Fix serialization of area and load_zone in buses

src/base.jl, test/test_powersystemconstructors.jl
This existing function does not work if the component has forecasts.
This is dependent on IS changes in https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/97
Let me know if you think `copy_forecasts` should be an exported PSY function.
=> Use copy_forecasts function to fix convert_component!

src/PowerSystems.jl, src/descriptors/power_system_structs.json, src/models/dynamic_generator_components.jl, src/models/generated/RoundRotorQuadratic.jl, src/models/generated/SalientPoleQuadratic.jl, src/models/generated/includes.jl, src/models/regulation_device.jl, test/test_dynamic_generator.jl
The following PR provides the two struct used for standard Round Rotor and Salient Pole (GENROU and GENSAL) models.
The saturation coefficients are computed using a specific function, that solves a quadratic equation directly.
=> Add Salient Pole and Round Rotor machine dynamic models

src/parsers/pm_io/psse.jl, src/parsers/power_models_data.jl, test/test_parse_psse.jl
The following PR adds in the ext of the parsed generators the value of R_source and X_source. These values are necessary to run dynamic simulations.
=> Add Impedance source in ext when parsing RAW files

src/base.jl, src/descriptors/power_system_structs.json, src/models/dynamic_branch.jl, src/models/dynamic_inverter.jl, src/models/dynamic_machines.jl, src/models/generated/Source.jl, src/models/generated/includes.jl, src/utils/power_flow/power_flow.jl, test/Project.toml
The following PR updates the Source struct to replace `activepower` with `active_power` and `reactivepower` with `reactive_power` as the new convention. It also add a Thevenin resistance, and includes a internal voltage and angle with default values that will be used for dynamic purposes. I also updated the test `Project.toml` file, to include `IS@0.12`.
In addition, I fix some problems with the set functions of RoundRotor Machines, and create the get and set functions for the DynamicBranch. However, there is a StackOverFlow problem with the `add_component!` with DynamicLines, detected in the `powerflow` test (Line 77). Any ideas here? This is the stacktrace:
```
test_powerflow: test set: Error During Test at /Users/rhenriquez/.julia/dev/PowerSystems/test/test_powerflow.jl:59
Got …
```
=> Update Source and Fix some typos

src/descriptors/power_system_structs.json, src/models/generated/RenewableDispatch.jl, src/utils/power_flow/power_flow.jl
The following PR fix the power flow solver to always work in system per unit, and then revert it back to the original one. It also fixes the issue with updating the solution in `system_base`, instead of `device_base`. I added a `@info` for the results exported in a DataFrame, to be clear that those results are exported in `system_base`.
=> Fix powerflow to update in device base

src/descriptors/power_system_structs.json, src/models/generated/HydroEnergyReservoir.jl, src/models/generated/includes.jl
Add new two parameters to deal with storage targets. A conversion factor was also added to deal with possible forecasts or data that is coming in `m^3` instead of `p.u.-hr`.
=> Add storage target and conversion factor to HydroReservoir

docs/src/modeler/data.md
@claytonpbarrows I'm finding these commands helpful for viewing your large systems before deciding whether I want to load them.
For example, this system.json is 127 MiB
```
jq '.data.components.Bus  | length' full_us_sys.json                                          
82000
jq '.data.components.ThermalStandard  | length' full_us_sys.json
8673
```
=> Fix jq examples for viewing serialized files

src/base.jl, src/models/OuterControl.jl, src/models/dynamic_branch.jl, src/models/operational_cost.jl, src/models/regulation_device.jl, src/models/serialization.jl
This PR adds support for serializing types that reside outside of PowerSystems. The serialization process adds a metadata dict to each component dict that includes module and type information.
This requires https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/122 and so tests will fail.
=> Serialize component modules

src/PowerSystems.jl, src/base.jl, src/parsers/TAMU_data.jl, src/parsers/pm_io/psse.jl, src/parsers/power_system_table_data.jl, src/utils/IO/system_checks.jl, test/test_power_system_table_data.jl, test/test_read_time_series.jl, test/test_system.jl
- Remove add_time_series! method that creates Deterministic and adds in
one step. Users now need to perform this individually.
- Support new NormalizationFactor type.
This removes add_time_series! methods that constructed Deterministic
and added it to the system in one step.
This is dependent on https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/125, and so tests will fail.
=> Add add_time_series! method that accepts multiple components

docs/src/modeler/parsing.md, src/PowerSystems.jl, src/base.jl, src/parsers/TAMU_data.jl, src/parsers/power_system_table_data.jl, test/runtests.jl, test/test_constructors.jl, test/test_powersystemconstructors.jl, test/test_read_time_series.jl, test/test_serialization.jl, test/test_system.jl
This updates PowerSystems to with the pre-10 branch of InfrastructureSystems.  It also requires the pre-10 branch of PowerSystemsTestData.
A number of things are commented out.  Leaving this as a draft until we workout what to do with them.
All tests pass except for 
- Some in test_read_time_series.jl.  These failures are due to an interface change in IS.read_time_series.  We currently don't have a way to convert PSY-supported time series CSV files into TimeArray objects.  Leaving this unresolved until we determine whether we want to restore the prior functionality.
=> Time series updates

docs/make.jl, docs/src/model_library/hybrid_device.md, src/PowerSystems.jl, src/models/HybridSystem.jl, test/test_hybrid_system.jl
This PR adds a basic struct for Hybrid Devices. Still doesn't address the addition to the system. 
Pending items:
=> add Hybrid System

src/descriptors/power_system_structs.json, src/models/generated/StaticReserve.jl, src/models/generated/StaticReserveNonSpinning.jl, src/models/generated/VariableReserve.jl, src/models/generated/VariableReserveNonSpinning.jl
Removes the wrong service costs added mainly [here](https://github.com/NREL-SIIP/PowerSystems.jl/pull/587). Correct approach was implemented in the [cost function update PR](https://github.com/NREL-SIIP/PowerSystems.jl/pull/596).
=> Remove wrong service costs

src/utils/network_calculations/ptdf_calculations.jl
This PR makes two small changes.
First, it replaces `S_` with `S` as it's not necessary to have a separate variable for that.
Second, it adds `@views` which makes a big difference in performance / memory allocation when calculating the PTDF for large systems.
=> Use views when concatenating PTDF matrix

src/models/supplemental_accessors.jl
closes #652 closes #649 @raphaelsaavedra after reviewing several references it seems that this is the best way to go ignoring the angle of the PST since the intended purpose of the PST is to change power flows and if the angle is included the PTDF becomes dependent on the system state. This will be consistent with Matpower and PowerWorld.
=> add fix to PTDF pst calculation

Project.toml
requires https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/175 to pass. But tests pass locally:
=> update project toml

src/PowerSystems.jl, src/base.jl, src/models/HybridSystem.jl, src/models/components.jl, src/models/regulation_device.jl, src/utils/print.jl
- Adding show method for PowerSystems Components that uses the getter function instead of get field
- Other change here is in `_get_multiplier` when unit settings is nothing  was to return 1.0 i.e DEVICE_BASE, now this is changed to NATURAL_UNITS.
- Changes to Test to reflect the changes in `_get_multiplier`
Requires IS#187 to be merged and tagged for Documentation to pass
=> Updating Printing 

docs/src/model_developer_guide/adding_custom_types.md, src/PowerSystems.jl, src/base.jl, src/parsers/power_models_data.jl, src/parsers/power_system_table_data.jl, src/utils/IO/branchdata_checks.jl, test/test_branchchecks_testing.jl, test/test_system.jl, test/test_validation.jl
1. Makes `System.runchecks` the only way to control validation of components. Deprecates the use of `skip_validation` in `add_component!`.
2. Adds functions to check components. Exports those functions along with `check!`.
3. Fixes a bug where the kwarg runchecks was not honored during deserialization.
Dependent on this InfrastructureSystems PR: https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/194.
=> Simplify system checks

src/base.jl
This PR addresses an issue with the following workflow:
- starting from a system with both `SingleTimeSeries` and `DeterministicSingleTimeSeries` (i.e. `transform_time_series` has been run)
- if you want to add a new time series, you need to remove all the `<:Forecast` time series first
- re-run `transform_time_series`
=> enabling the removal of system time series of a particular type

src/base.jl, test/test_system.jl
=> Preserve runchecks across deepcopy

src/PowerSystems.jl, src/base.jl, src/models/HybridSystem.jl, src/models/static_injection_subsystem.jl, test/common.jl, test/test_hybrid_system.jl, test/test_serialization.jl
This PR adds the following functionality for HybridSystems:
- Add supertype StaticInjectionSubystem.
- Perform the `mask_component!` operation on subcomponents when the Hybrid is added to the system. This allows all time series methods to work on the subcomponents.
- Add serialization support.
=> Add full support for HybridSystems

src/models/supplemental_constructors.jl, test/test_cost_functions.jl
For easier use with generators that are not multi-stage
Based on a [slack conversation](https://app.slack.com/client/T018DC9RCDV/C019J02EHNU/thread/C018SP6N7SR-1620141073.002600). This allows passing a single `start_up` value to `MarketBidCost`, for easier use with generators that are not multi-stage. We still repesent start-up costs internally as a NamedTuple (with hot/warn/cold values, as in the Market Bid Forms), but allow passing a single value that sets only the `hot` value, because this is what operators use when they don’t have multiple stages.
- i ran the formatter, but let me know if there are any style comments. 
- i use `cost.start_up` in the tests because equality is not defined on `MarketBidCost` (so couldn't do `MarketBidCost(; startup=X, ...) == MarketBidCost(; …
=> Allow passing single `start_up` value

src/base.jl
Older versions of data did not include the field `masked_components` and
the code was not accounting for that fact. This caused a runtime
exception.
=> Fix deserialization to account for old datasets

src/utils/network_calculations/ptdf_calculations.jl
Currently it just throws an enigmatic `BoundsError: attempt to access 0-element Vector{Int64} at index [1]`.
=> Add error message when calculating PTDF for a system without reference bus

src/parsers/power_models_data.jl
The previous implementation miscalculated the value of the rating in RenewableDispatch
=> fix rating calculation

src/base.jl, test/test_system.jl
This PR fixes #762. It will also make deepcopy of a system with HDF5 time series data much faster because there will not be a serialize and deserialize.
This requires https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/242. CI will fail until a new IS tag is available. The Project.toml will have to require that new tag.
=> Optimize deepcopy of System

src/descriptors/power_system_structs.json, src/models/generated/SEXS.jl
Fix a bug in SEXS struct that should have V_ref.
=> add V_ref to SEXS struct

docs/src/modeler_guide/system.md, src/PowerSystems.jl, src/base.jl, test/common.jl, test/test_power_system_table_data.jl, test/test_serialization.jl, test/test_system.jl
This PR does two things:
- Fixes NREL-SIIP/PowerSystems.jl#604
- Adds an option to generate new UUIDs during deserialization.
The default behavior for `compare_values` is now to ignore UUIDs by default. We still use this to compare all values during serialization/deserialization.
The use case this addresses is the following:
```
sys1 = PSB.build_system(PSB.PSITestSystems, "test_RTS_GMLC_sys")
sys2 = PSB.build_system(PSB.PSITestSystems, "test_RTS_GMLC_sys")
gen1 = first(get_components(ThermalStandard, sys1))
gen2 = first(get_components(ThermalStandard, sys2))
set_active_power!(gen1, get_active_power(gen1) + 0.1)
PSY.compare_values(gen1, gen2)
┌ Error: values do not match
│   T = ThermalStandard
│   name = :active_power
│   val1 = 0.65
│   val2 = 0.55
└ @ PowerSystems …
```
=> Compare values

docs/make.jl, docs/src/modeler_guide/power_flow.jl, src/utils/power_flow.jl
The following code closes #782 by allowing all StaticInjection to be used in PV Buses. In addition, it allows to split the power based on the `base_power` if multiple devices are connected in the same PV or REF bus.
=> Fix Powerflow issues

src/descriptors/power_system_structs.json, src/models/generated/PeriodicVariableSource.jl
Don't need available field for the PeriodicVariableSource because the availability will come from the StaticInjector it is connected to?
=> Remove available field from PeriodicVariableSource

docs/src/modeler_guide/system.md, src/utils/print.jl
There are no functional changes here; just additions to docstrings and the docs.
=> Add examples for show_components

src/base.jl, src/parsers/power_models_data.jl, test/test_system.jl, test/test_validation.jl
Adds new methods to `check_components` in order to allow PowerSimulations to perform checks on specific component types.
Also updates docstrings for a changed exception in IS.
=> Add check_components method

src/descriptors/power_system_structs.json, src/models/generated/VirtualInertia.jl
The change flips two states for the purpose of standardizing that order in PSID.
This should break PSID, that is fixed In another PR.
=> Change order of VirtualInertia states

src/models/HybridSystem.jl, src/models/serialization.jl
This fixes a bug when deserializing a HybridSystem that has a interconnection_impedance with a complex number instead of nothing.
=> Fix serialization of Union types with Nothing

src/PowerSystems.jl, src/base.jl, src/models/static_injection_subsystem.jl, test/test_hybrid_system.jl
The purpose of this PR is to make HybridSystem subcomponent time series available at the HybridSystem for use in PowerSimulations. If you add a HybridSystem with subcomponents already attached to the System then the HybridSystem will have references to the their time series in the format `<typeof(subcomponent)>__<time_series_name>`.
There is one possible problem with this solution. If the user adds time series data to a subcomponent _after_ adding the HybridSystem to the System then it is up to that user to call `copy_subcomponent_time_series!`. Is this a deal breaker?
=> Add subcomponent time series to subsystem

src/parsers/pm_io/psse.jl, src/parsers/pm_io/pti.jl
This PR corrects cases where the base voltage of a transformer is set to 0.0. PSS/e and mat power allow for these cases x-ref issue: #853 
@ccoffrin let me know if you want me to open a PR in PowerModels with this update or address it in a different way.
=> add parsing checks base impedance 

src/base.jl, test/test_system.jl
This follows the Julia parameter-order convention where a function is listed first so that do blocks can be used for the function.
The existing implementation is unchanged, so users can choose their preferred way of using the feature.
=> Add get_components method with filter_func

src/models/dynamic_generator_components.jl
The following fix a bug on the checking when to neglect saturation
=> Fix saturation bug

src/parsers/psse_dynamic_data.jl
The PR fix a bug to properly set-up the R_th and X_th of a Source Model in a system base instead of a Machine base.
=> Fix Source R and X source base values

src/parsers/power_system_table_data.jl
The PowerSystems table parsing has O(n^2) complexity for parsing batteries, where every row of the storage data frame is iterated or each battery. This pull request creates a map to the storage head and tail instead as a preprocessing step.
=> Speed-up battery parsing

src/utils/network_calculations/ybus_calculations.jl
- Doesn't check connectivity if the system has only one node.
=> only check connectivity for multiple nodes

src/utils/print.jl, test/test_printing.jl
This is a redo of #978 which had some commits from another PR.
Fixes https://github.com/NREL-SIIP/PowerSystems.jl/issues/973.
@rodrigomha Here is how this shows up. We could print other fields, reverse the order of these two fields. Let me know what you'd like.
```
215_HYDRO_3 (HydroEnergyReservoir):
name: 215_HYDRO_3
available: true
bus: Barton (Bus)
active_power: 0.5
reactive_power: 0.16
rating: 0.5249761899362675
prime_mover: PrimeMovers.HY = 16
active_power_limits: (min = 0.0, max = 0.5)
reactive_power_limits: (min = -0.1, max = 0.16)
ramp_limits: (up = 0.5, down = 0.5)
time_limits: (up = 0.0, down = 0.0)
base_power: 100.0
storage_capacity: 20.0
inflow: 4.0
initial_storage: 10.0
operation_cost: TwoPartCost
storage_target: 1.0
conversion_factor: 1.0
time_at_status: 10000.0
services: …
```
=> Improve printing of time series instances

src/parsers/power_system_table_data.jl
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR: 
Check the [contributor guidelines](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Fix tabular data parser to parse _must_run_  for **ThermalStandard**
2. [Issue Fix](https://github.com/NREL-SIIP/PowerSystems.jl/issues/981)
closes #981
=> Fix ThermalStandard must_run in tabular data parser

src/descriptors/power_system_structs.json, src/models/generated/ReserveDemandCurve.jl, src/models/generated/StaticReserve.jl, src/models/generated/StaticReserveNonSpinning.jl, src/models/generated/VariableReserve.jl, src/models/generated/VariableReserveNonSpinning.jl, src/models/generated/includes.jl
Adding two new fields to Reserve objects, `sustained_time` the amount of time the reserve contribution must be provided for and `max_participation_factor` the maximum share of reserve product a single device can provide.
=> Updating Reserve structs

src/PowerSystems.jl, src/descriptors/power_system_structs.json, src/models/dynamic_inverter.jl, src/models/dynamic_inverter_components.jl, src/models/generated/InstantaneousCurrentLimiter.jl, src/models/generated/MagnitudeCurrentLimiter.jl, src/models/generated/PriorityCurrentLimiter.jl, src/models/generated/includes.jl, test/Project.toml, test/test_dynamic_inverter.jl
Currently is not working. I think is related to having an abstract type in the limiter field of the `DynamicInverter` struct.
=> Add current lims to psy3

src/base.jl, src/deprecated.jl, test/test_deprecations.jl, test/test_powersystemconstructors.jl
This will be used for a new system in PowerSystemCaseBuilder. Includes unit tests.
---
- Define convert_component! for conversions from PowerLoad to StandardLoad
- Add unit tests for this method along the lines of existing convert_component! unit tests
- Refactor convert_component! unit tests to remove repetition
=> Implement convert_component! for StandardLoad <- PowerLoad

src/parsers/pm_io/psse.jl, src/parsers/power_models_data.jl
=> correct tap transformer calculation

src/base.jl, test/test_serialization.jl
=> Fix serialization of System.frequency

src/parsers/powerflowdata_data.jl
Given the way that the PowerFlowData is structured, it isn't possible to use formatter for these kinds data inputs.
=> change the bus name convention

Project.toml, src/parsers/common.jl
`parse_enum_mapping` was converting input to uppercase but the keys of the underlying dictionary were not all uppercase, so, e.g., `parse_enum_mapping(PrimeMovers, "PVe")` wouldn't work and https://github.com/NREL-Sienna/PowerSystems.jl/issues/849 wasn't truly solved. Now everything is `Unicode.normalize(casefold=true)`'d on both sides.
=> Fix case sensitivity in enum parsers

src/PowerSystems.jl, src/base.jl, src/subsystems.jl, test/common.jl, test/test_serialization.jl, test/test_subsystems.jl
This requires InfrastructureSystems code from https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/326. So, CI will fail.
=> Add support for subsystems

src/utils/print.jl
=> add print method for operational cost types

docs/src/modeler_guide/parsing.md
1. Added a section to the parsing.md documentation file addressing common issues when parsing PSS/e data. 
Added a guide to working around non-unique PSS/e bus names. 
2. This is not fixing an open issue.
3. This does not contribute a new struct.
=> Add bus_name_formatter to documentation

src/base.jl, test/test_validation.jl
This fixes a regression from #1047 (pys4 branch). When we added checks for subsystems we inadvertently caused components to get checked twice, producing duplicate error messages.
=> Remove duplicate check

test/test_subsystems.jl
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR:
Check the [contributor guidelines](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Add a description of the changes proposed in the pull request.
2. Is my PR fixing an open issue? Add the reference to the related issue
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)
=> Fixing the failed test

src/PowerSystems.jl
The second part of a significant refactor of Sienna cost data structures (part 1 is [here](https://github.com/NREL-Sienna/PowerSystems.jl/pull/1056#issuecomment-1959057500)). The main focus here is to bring PowerSimulations.jl up to date with the elimination of `VariableCost` in favor of `FunctionData`. That entails these changes in PowerSystems:
- Add exports for the new "raw data" functions added to `FunctionData`
Tests pass:
=> Variable Cost Refactor Part 2: PowerSimulations

test/test_generate_structs.jl
This test was failing when the package was installed by cloning a git branch, which causes all source files to be read-only. Copy/edit of the descriptor file in this test would then fail.
=> Ensure that the test file can be overwritten

src/models/static_injection_subsystem.jl, src/utils/print.jl
This is a follow-on to #1073. There were cases where we were using nameof (which removes parameteric types) where we should have used strip_module_name (which preserves parametric types). The best example is when printing a table of component counts. We were showing VariableReserve twice instead of showing both VariableReserve{ReserveDown} and VariableReserve{ReserveUp}.
=> Resolve nameof vs strip_module_name

src/models/components.jl, test/test_dynamic_generator.jl
Add a getter function to support the fix for https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1064, test it.
=> Support fix for PowerSimulations #1064

docs/src/modeler_guide/time_series.md, src/PowerSystems.jl, src/base.jl, test/test_system.jl
At least partially fixes #1076 
Tied to https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/341
=> Allow bulk writing and reading of time series

src/base.jl, test/test_dynamic_generator.jl, test/test_dynamic_loads.jl, test/test_system.jl, test/test_validation.jl
Fixes #1016. The check for whether a component is attached to a system was inadequate. It checked whether a component of the given type and name was attached to the system. If you built two systems with the same components and names, that check would incorrectly pass. This PR fixes that bug.
There were numerous tests that only passed because of this same-type-and-name comparison. This PR also fixes those tests.
=> Fix component-is-attached-to-system check

src/parsers/power_models_data.jl, test/test_parse_psse.jl
Removed if statement from the read_loads!() function that caused StandardLoads being read from .mat and .raw files to be dropped if the constant_active_power and constant_reactive_power arguments were 0. 
This is correcting issue #1032
=> Repair StandardLoad parsing from .mat/.raw files

src/PowerSystems.jl, src/models/cost_functions/HydroGenerationCost.jl, src/parsers/power_models_data.jl
Miscellaneous cleanup:
1. Remove the import from IS of `get_raw_data` as it no longer exists
2. Make the hydro cost struct default constructor use a `CostCurve` as it is simpler to deal with
=> More Miscellaneous Costs Cleanup

src/models/cost_functions/StorageCost.jl
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR:
Check the [contributor guidelines](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)
1. Add a description of the changes proposed in the pull request.
2. Is my PR fixing an open issue? Add the reference to the related issue
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)
=> change getters

src/PowerSystems.jl, src/models/cost_function_timeseries.jl, src/models/cost_functions/variable_cost.jl, test/test_cost_functions.jl
This PR implements an interface to get at the fuel cost fields within the new cost structs. I took inspiration from the existing variable cost time series interface for `MarketBidCost`. Depends on https://github.com/NREL-Sienna/PowerSystems.jl/pull/1100, that should be merged first.
=> Fuel Cost Interface, Including Time Series

src/PowerSystems.jl, src/models/cost_function_timeseries.jl, src/models/cost_functions/MarketBidCost.jl, src/models/cost_functions/ValueCurves.jl, src/models/cost_functions/variable_cost.jl, test/test_cost_functions.jl
Depends on https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/367. Here we:
- Add a validation function `is_market_bid_curve` and factory function `make_market_bid_curve` to deal with market bid curves, which are `CostCurve{PiecewiseIncrementalCurve}`s with `NaN` first x-coordinate and initial input.
- Make the market bid cost time series return time arrays of these objects, even though they must be constructed with time series of `FunctionData`.
- Rewrite `cost_function_timeseries.jl` so that less logic has to be duplicated for every new field that works this way
- Make `no_load_cost` and `start_up` fields of `MarketBidCost` work this way
=> Renovate time series functionality for `MarketBidCost`

src/models/cost_functions/operational_cost.jl, src/models/cost_functions/variable_cost.jl, src/models/serialization.jl, test/test_serialization.jl
This small PR:
- Fixes https://github.com/NREL-Sienna/PowerSystems.jl/issues/1081 by using existing `Component` serialization code to ensure that the vector of `Service`s in `MarketBidCost` gets serialized as UUIDs, adds a test for serialization of `MarketBidCost` with `Service`s
- Fixes a variable cost constructor ambiguity introduced in https://github.com/NREL-Sienna/PowerSystems.jl/pull/1112 (@rodrigomha for visibility; can you verify that this solution works for you?)
=> Fix issue 1081, fix bug from PR 1112

src/PowerSystems.jl, src/models/cost_functions/cost_aliases.jl, src/models/cost_functions/variable_cost.jl, test/test_cost_functions.jl
The main goal here, discussed with @rodrigomha, is to allow a user of the `ValueCurve` cost aliases to get everything they need without unwrapping to the `FunctionData`. I also cleaned up some docs and tests that were outdated due to a VOM cost refactor. I didn't fix this failure, which I assume is due to changes elsewhere:
---
Adding @kdayday as a reviewer of these added semantics:
- `get_slopes(::PiecewisePointwiseCurve)`  _calculates_ the slopes from the underlying pointwise `FunctionData`
- `get_slopes(::PiecewiseIncrementalCurve)` _fetches_ the slopes == the y-coordinates of the underlying step `FunctionData`
- `get_average_rates(::PiecewiseAverageCurve)` _fetches_ the average rates == the y-coordinates of the underlying step `FunctionData`
=> Add Cost Alias Getters

src/data_format_conversions.jl
Not because we've committed to providing these, but I wanted the converted version of a system anyway. Briefly ran the storage math by @rodrigomha but would appreciate a more formal review.
=> Add some more PSY 3 -> PSY 4 system conversions

src/descriptors/power_system_inputs.json, src/parsers/power_system_table_data.jl
I've replicated the PSY3.0 objective function created by the tabular parsing of the RTS using the `FuelCurve` functionality.  However, I haven't developed tests. In the interest of time, I'm opening this PR now.
=> fixing tabular parser

src/PowerSystems.jl, src/models/cost_functions/ValueCurves.jl, src/models/cost_functions/cost_aliases.jl, test/test_cost_functions.jl
Discussing with @jd-lara et al., it sounds like in certain cases we need to be able to explicitly represent a no-load cost as part of a cost curve instance, even if that cost is not part of the representation of the actual… cost curve. For instance, some input formats define a no-load cost and *do not* define a cost at minimum generation, and (roughly) you're supposed to infer the latter from the former by assuming the data is quadratic. Here we:
- Add `input_at_zero` to all `ValueCurve` subtypes to maintain the isomorphic design, but only expose it to the user through the simplified cost alias interface as part of `PiecewiseIncrementalCurve` because that is the only place we expect it to be used. It defaults to `nothing` if not specified and is preserved under all conversions.
- Add …
=> Add `input_at_zero` to cost functions

src/PowerSystems.jl, src/base.jl, test/test_topology.jl
For PowerAnalytics/`ComponentSelector`-related reasons, it is useful to be able to test whether a given `Component` is within a given `AggregationTopology` without having a reference to the relevant `System`. This exposes that functionality. I also made the existing `get_component_in_aggregation_topology` test more thorough.
=> Add `is_component_in_aggregation_topology`

docs/src/api/public.md
Quick fix to add the cost alias getter/setter functions to the Public API (cost_aliases.jl)
=> Add cost alias functions to public API

docs/src/api/valuecurve_options.md, docs/src/explanation/example_dynamic_data.md, docs/src/explanation/system.md, docs/src/explanation/type_structure.md, docs/src/tutorials/working_with_time_series.md
This breaks the docs pictures for my local build, but matches Rodrigo's suggestions and the previous format.
=> Update asset directory for picture links

src/PowerSystems.jl, src/descriptors/power_system_inputs.json, src/parsers/power_system_table_data.jl, test/test_power_system_table_data.jl
Currently only works for heat rate and not cost curves.
- Added new fields for generators to capture quadratic heat rate curve. For simplicity, the names are `heat_rate_a0`, `heat_rate_a1`, `heat_rate_a2`. All of the new fields are `null` by default. Open to suggestions on the nameing,
- If any `heat_rate_a*` column are defined, then we call `create_poly_cost` for `ThermalGen`,
- `create_poly_cost` will return 
- `QuadraticCostCurve` if all the coefficients are passed
- `LinearCurve` if `a1` and `a0` is passed,
- `LinearCurve` if `a1`  is passed,.
- raise an Error if `a2` is passed but `a1` or `a0` is nothing,
Closes #1177
=> fix: Adding support for quadratic functions using the table data parser

src/base.jl
Fixes #1203 
The function get_buses would fail with an unhandled exception if any bus did have an AggregationTopology assigned.
=> Fix get_buses when a bus does not have an AggregationTopology

src/models/components.jl
Before:
After:
On the current `@scoped_enum` implementation, `UnitSystem.NATURAL_UNITS` isn't a constant, it's a dictionary lookup — one that incurs 80 bytes of memory allocation. Thus you can see the performance impact piling up in the "before" case in the order in which the unit systems are checked — `DEVICE_BASE`, then `SYSTEM_BASE`, then `NATURAL_UNITS`. There are a few ways one might fix this:
1. Alter `@scoped_enum` to make `UnitSystem.NATURAL_UNITS` behave more like an immutable struct lookup, either by actually making it one or doing something to clue the compiler into the fact that it will never change. This would be the best, most holistic solution, but I couldn't immediately figure out how we might do it without completely overhauling `@scoped_enum`. I'll keep it in the back of …
=> PERF: dispatch on `UnitSystem` value in `_get_multiplier`

src/parsers/power_models_data.jl
Currently if data has 0 base power for units, the conversion default to NaN.
=> Fix Matpower base power parser

docs/src/explanation/per_unit.md, docs/src/tutorials/creating_system.md, src/PowerSystems.jl, src/base.jl, test/test_system.jl
Closes https://github.com/NREL-Sienna/PowerSystems.jl/issues/1229 by adding a new exported function `with_units_base` that serves as a "context manager" to execute a block of code as if the system's units base were set to a particular value.
=> Add `with_units_base` feature

src/base.jl
This bug caused a converted/copied component to have references to system objects. This fix is required before this IS PR can be released: https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/424
=> Fix bug in convert_component

docs/src/explanation/per_unit.md, docs/src/tutorials/creating_system.md, src/PowerSystems.jl, src/base.jl, src/descriptors/power_system_structs.json, src/models/generated/Transformer3W.jl, src/models/generated/includes.jl, src/parsers/power_system_table_data.jl, test/test_system.jl
Initial idea for 3W transformer based on PSSE.
We are not giving support to any tap voltage control (i.e. `COD1 = COD2 = COD3 = 0`), and we are assuming that all the data must come in system per unit. These requires the flags `CW = CZ = CM = 1`.
=> [DRAFT] [PSY5] Add 3W Transformer Struct

src/PowerSystems.jl, src/base.jl, test/test_dynamic_generator.jl, test/test_system.jl
This feature constitutes the PSY implementation of https://github.com/NREL-Sienna/PowerSystems.jl/issues/1231. It adds a function `fast_deepcopy_system` that makes a `deepcopy` of a `System` more quickly by skipping the copying of time series and/or supplemental attributes. As part of the implementation, I also fix issue #1233.
Depends on https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/421.
=> Add `fast_deepcopy_system` function, fix bug 1233, fix `compare_values` bug

docs/src/how_to/improve_ts_performance.md, src/PowerSystems.jl, src/base.jl, test/common.jl, test/test_dynamic_generator.jl, test/test_system.jl
CI will fail until this PR is merged and tagged: https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/416
=> Add support for InfrastructureSystems methods for time series and supplemental attributes transactions

docs/src/api/public.md, src/PowerSystems.jl, src/base.jl, src/component_selector.jl, src/get_components_interface.jl, src/utils/print.jl, test/common.jl, test/test_component_selector.jl, test/test_powersystemconstructors.jl, test/test_system.jl
Successor to https://github.com/NREL-Sienna/PowerSystems.jl/pull/1079 and companion to/depends on https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/342. Adds an immutable, lazy, system-independent representation of a grouped set of components. For more details and a demonstration, see https://github.nrel.gov/gkonars/PowerAnalytics-demos/blob/main/component_selector_pr_demo.ipynb.
=> Add `ComponentSelector` feature: PSY portion (take two)

src/descriptors/power_system_structs.json, src/models/generated/Source.jl
Fixes https://github.com/NREL-Sienna/PowerSystems.jl/issues/1164 as it pertains to `Source`.
=> Address issue 1164 for `Source` by adding `needs_conversion`

src/PowerSystems.jl, src/base.jl, src/parsers/power_models_data.jl, src/parsers/psse_metadata_reimport.jl
Here, I implement logic such that when `System("my_filename.raw")` is called, PowerSystems will check for a `my_filename_export_metadata.json` file written by the PowerFlows.jl PSS/E exporter in the same directory and, if it is found, use its contents to undo the system alterations PowerFlows had to make to write to the PSS/E format. The goal is for systems loaded this way to look as similar to the original system that was serialized as possible. The user can opt out of this feature by passing `try_reimport = false`. There is also interface to manually pass a metadata dictionary to perform this same remapping.
In the process of implementation, I also added a `area_name_formatter` System constructor kwarg along the same lines as https://github.com/NREL-Sienna/PowerSystems.jl/issues/1160. …
=> Read export metadata file for round trip with PowerFlows.jl's PSS/E exporter

src/PowerSystems.jl, src/base.jl
* Export IS.get_time_series_summary_table to be used by SiennaPRASInterface and also prints length when system time series summary is pretty printed.
=> Export IS.get_time_series_summary_table

src/parsers/pm_io/data.jl, test/test_parse_psse.jl
Adding rescaling for ZIP StandardLoad parameters that were missing (current_active_power, current_reactive_power, impedance_active_power, impedance_reactive_power)
=> adding per_unit conversion for zip load

src/base.jl, src/definitions.jl, src/models/cost_function_timeseries.jl, src/models/cost_functions/MarketBidCost.jl, test/test_cost_functions.jl
`MarketBidCost.start_up` could already be set to a time series; here I add that feature to `MarketBidCost.shut_down`. I also clean up the startup cost interface a little: allow the user to call `set_start_up!(::System, ::StaticInjection, data)` with `Float64` data (they could already call `set_start_up!(::StaticInjection, data)` with `Float64` data), etc.
I think this could be added to PSY4 as a minor update, it doesn't seem like it needs to wait until PSY5, unless that would make things too chaotic.
=> `MarketBidCost`: let `shut_down` be a time series, clean up startup cost interface

src/parsers/pm_io/psse.jl, src/parsers/power_models_data.jl
- The new keys "psw" and "qsw" where added in the parser as the active and reactive power flow respectively, since these in particular are necessary for parsing the file.
-  There were some problems creating the key "ext" when converting a branch to a 2W transformer for bus voltage differences.
- A small logic was added to keep considering the elements as branches if the threshold of 1kV is not exceeded, otherwise it will be considered as a 2W transformer and an empty "ext" dict is added.
- Improve of the warning statement to see the voltage difference and in which buses this is happening.
=> Bug fixes for reading MMWG files

src/parsers/power_models_data.jl, test/test_parse_psse.jl, test/test_system.jl
- There's were some issues with the tests due to the parsing of the area interchanges, since matpower files does not define these properly.
- Some tests were updated to match the switch shunts naming.
=> Fix matpower files parsing bug and update tests

src/base.jl, src/descriptors/power_system_structs.json, src/models/generated/ExponentialLoad.jl, src/models/generated/PowerLoad.jl, src/models/generated/StandardLoad.jl, src/models/generated/includes.jl, src/parsers/pm_io/matpower.jl, src/parsers/pm_io/psse.jl, src/parsers/power_models_data.jl, test/test_parse_psse.jl
An is_conforming Bool field was added to the structs of StaticLoad subtypes. All tests are passing in psy5
=> Adding load conforming field

src/parsers/power_models_data.jl
This is a small change to avoid conflicts with the tests in PowerFlows psse exporter.
=> Revert shunt (fixed and switched) naming

src/parsers/power_models_data.jl, src/parsers/psse_dynamic_data.jl, test/test_parse_psse.jl
We were getting problems with serializing named tuples.
Do you think this approach is okay @jd-lara ? We could also add in the ext, `r_source` and `x_source` rather than `r` and `x`?
=> Fix parse psse test

README.md
RTS GMLS main branch is master, not main. See https://github.com/GridMod/RTS-GMLC/tree/master/RTS_Data/SourceData
=> Fix RTS GMLC link from main to master

src/parsers/powerflowdata_data.jl
Adding missing base_power field to TapTransformer component in powerflowdata_data file. Error is triggered when parsing the PSSE 30 Test System.
=> Adding missing base_power field 

src/parsers/common.jl
Ensure that if alpha != 0 in the pm_data, the component is parsed as a `PhaseShiftingTransformer`.
With this change, the Ybus matches matpower for the ACTIVSg10k case when parsing the .m file directly.
=> check alpha == 0 for transformer2w

src/base.jl, src/parsers/pm_io/common.jl, src/parsers/pm_io/data.jl, src/utils/IO/system_checks.jl
Removes the modifications of bus types depending on the connected generators during parsing.
Instead, logs errors during the system checks.
@jd-lara Should this definitely be an error and not a warning? This causes errors to be logged in various systems used in the tests:
=> Remove bus modifications during parsing 

src/parsers/pm_io/psse.jl, src/parsers/power_models_data.jl
Adds a field to the bus PowerModels dictionary to indicate a bus should be skipped when building the system. This is used for dummy buses that are part of multi-section lines. 
Closes #1429
=> Don't add dummy buses to system

src/parsers/generator_mapping.yaml, src/parsers/pm_io/psse.jl, src/parsers/power_models_data.jl, test/test_parse_psse.jl
Closes https://github.com/NREL-Sienna/PowerSystems.jl/issues/1433
=> Parse gens as Synchronous Condensers under given conditions

src/descriptors/power_system_structs.json, src/models/generated/TwoTerminalLCCLine.jl, src/parsers/pm_io/psse.jl
- @hannahchubin found the bug on the docstrings for the "compounding_resistance" field, where it wasn't set to the right description.
- The previous "EXT" field is being lowercased.
- the ext for v35 NDR field was added instead of the duplicated NDI.
=> Small bug fixes found in LCC fields

src/outages.jl
This PR aims to add a new abstract type called "UnplannedOutage" which includes GeometricDistributionForcedOutage and FixedForcedOutage.
This is intended  to facilitate the implementations of Security-Constrained Unit-Commitment in PSI.
The outage tests were run locally and those passed.
*When I ran the formatter I notices it corrected a lot of markdowns.
=> add new abstract typo "UnplannedOutage" for GeometricDistributionForcedOutage and FixedForcedOutage.

src/parsers/pm_io/psse.jl, src/parsers/pm_io/pti.jl, src/parsers/power_models_data.jl
- The V35 PJM files were missing the OWNER data, which were manually fixed.
- The 3w parameters were missing a conditional to be added to the ext.
- The IC data in PJM file is a bit different from the ones we've been working with, requiring an extra step to handle it with the parser.
closes #1536
=> Fix bugs found in V35 PJM file
